<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [4]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [5]:
random_array = np.random.randint(0, 1000, 100)

print(random_array.min())
print(random_array.max())
print(random_array)

1
998
[ 33 176 751   6 488 895 266 623 455 195 499 566 358 137 187 380 666 439
 274 114 117 668 689  26 944 992 171 515 324 161 144 795 134 897 575 306
 324 393 881 652 675 866 239 831 544 359 774  39 657 254 385 842 195 598
 887 685 970 475 281 803 367 922 988 869 743 411 355 259 674  36 409 286
 184 521 868 998 757 878 421 600 303 440 521 660 313 797 133   1 188 114
 384 640 780 245 679 902 663 997 901 476]


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [3]:
vetor1 = np.array([22,70])

def CalculaModulo(vetor):

    modulo_quadratico = np.linalg.norm(vetor)

    return modulo_quadratico

CalculaModulo(vetor1)

73.37574531137656

## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [11]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

In [10]:
# Solução
def calculate_eqm(y_prediction, y_i):
    return np.mean((y_prediction - y_i)**2)

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [16]:
array2 = np.ones((3, 3))
array2[1][1] = 0
array2

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [25]:
array3 = np.array(([1,2,3], [4,5,6]))
print(array3)
array0 = np.zeros((4, 5))
array0[1][1:4] = array3[0]
array0[2][1:4] = array3[1]
array3 = array0
print(array3)

[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 0. 0. 0. 0.]]


## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [27]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [ ]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

(64, 512)

In [ ]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-53.08727366483029

In [ ]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])

In [ ]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

In [30]:
# Solução
import numpy as np

def matriz_processada(x):
    media = np.mean(x, axis=0)
    x_corrigido = x - media
    return x_corrigido


X_processado = matriz_processada(X)
print(X_processado)


[[ 0.3419381  -0.80518163  0.31126881 ... -1.15996995 -0.46358558
   0.32792516]
 [-0.05050525 -0.05514934 -0.92009369 ... -1.64349051 -0.30880259
  -0.36545193]
 [-0.04499346  0.3714249  -1.20845552 ...  0.47828958 -0.9638009
   0.33095709]
 ...
 [-0.62620052 -0.30625385  1.38878122 ... -0.46450908  0.4800182
   1.60351203]
 [-1.65378615  0.8703366   0.85538338 ...  0.91090713  1.28872964
  -1.66435692]
 [ 0.84278556  0.13603146  0.2166403  ... -0.04198981  0.34131539
   1.7820119 ]]


## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [5]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[-1.39968514,  0.89816165,  0.10742209, ...,  0.53805522,
        -1.53378568,  1.00249105],
       [-0.243645  , -0.02966371, -1.77779711, ...,  1.54037045,
        -0.45059013,  0.4268144 ],
       [-1.15709793, -2.44135288,  0.03259105, ...,  0.38204005,
         0.42558792,  0.17195153],
       ...,
       [ 0.71306474, -1.93908364,  1.09465012, ...,  1.09781094,
        -0.27434575,  1.01090882],
       [-0.68977708,  0.84967718, -0.83374975, ..., -1.84152133,
         1.11118093, -0.04475883],
       [ 0.35197572,  1.1761252 ,  0.05541569, ...,  3.83988914,
         1.21383178,  0.16608572]])

In [13]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [14]:
is_outlier

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False]])

In [15]:
outliers_count

10

In [10]:
outliers

array([-3.08139403, -2.96891255,  3.98631002, -2.96237833, -2.80977126,
        3.30993024,  3.22129013,  3.13311253,  3.18505983,  3.83988914])

In [11]:
# Solução

def locate_outliers(vetor):
    mean = np.mean(vetor, axis=0)
    std = np.std(vetor, axis=0)
    is_outlier = np.abs(vetor - mean) > 3 * std
    outliers_count = np.sum(is_outlier)
    outliers = vetor[is_outlier]
    return is_outlier, outliers_count, outliers


## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [17]:
q8 = np.arange(1, 22, 2)
q8

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [21]:
np.random.randint(0, 100, 10)


array([37, 92, 15, 44, 85, 42, 39, 86,  5, 53])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [22]:
def normalizacao(vetor):
    std = vetor.std()
    media = vetor.mean()
    normalizado = (vetor - media) / std
    return normalizado

normalizacao(q8)

array([-1.58113883, -1.26491106, -0.9486833 , -0.63245553, -0.31622777,
        0.        ,  0.31622777,  0.63245553,  0.9486833 ,  1.26491106,
        1.58113883])

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [35]:
notas = np.random.randint(0, 100, 100)/10
print(notas)
def AnaliseNotas(vetor):
    media = vetor.mean()
    desvio = vetor.std()
    maior7 = np.unique(np.where(vetor >= 7), return_counts=True)
    reprovados = np.unique(np.where(vetor < 5), return_counts=True)
    maior = vetor.max()
    menor = vetor.min()
    lista = [media, desvio, np.sum(maior7[1]), np.sum(reprovados[1]), menor, maior]
    return np.array(lista)

AnaliseNotas(notas)

[0.6 0.1 9.7 0.7 0.4 8.3 7.5 9.7 2.3 8.2 6.3 5.7 0.2 4.3 2.3 4.4 9.6 3.8
 6.4 4.7 1.2 9.7 7.8 5.6 7.4 5.8 3.9 9.9 0.3 8.7 5.8 8.3 9.9 3.4 7.1 1.1
 1.9 5.9 0.3 1.4 9.2 3.3 9.7 8.9 1.4 2.5 1.5 6.  7.9 5.7 9.7 8.3 6.5 9.4
 2.2 8.6 2.6 1.6 1.7 3.6 6.7 7.1 3.  5.  2.3 9.  3.6 1.4 2.3 2.7 5.3 3.6
 7.7 6.7 1.6 7.5 8.3 6.4 3.5 2.2 4.1 4.8 5.1 4.2 7.4 7.6 7.1 3.3 9.5 7.7
 6.1 2.9 4.4 2.5 8.8 8.4 6.6 8.4 3.3 0.3]


array([ 5.193    ,  2.9622375, 35.       , 47.       ,  0.1      ,
        9.9      ])